name: Cmake-ci

'on':
    pull_request:
    push:
        branches:
          - master
          - dev*
          - feature/**

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
    MSVC:
        runs-on: windows-2019
        name: windows-2019
        strategy:
            fail-fast: false
            matrix: 
               os: [windows-2019]


        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0
          - uses: actions/setup-python@v4
            with:
                python-version: '3.10' 
                cache: 'pip' # caching pip dependencies
          - name: Conan detect
            run: |
                pip install "conan>=1.51.0,<2.0.0"
                conan profile new --detect default

          - name: Run conan
            run: |
                mkdir ${{github.workspace}}/build
                conan install  . --build=missing -pr:b=default -if ${{github.workspace}}/build
          - name: Configure CMake
            run: >-
                cmake -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}"
                -DCMAKE_PREFIX_PATH:PATH=${{github.workspace}}/build/generators
                -DCMAKE_MODULE_PATH:PATH=${{github.workspace}}/build/generators
                -Dagg_BUILD_CONTROLS:BOOL=ON
                -Dagg_BUILD_DEMO:BOOL=ON
                -Dagg_BUILD_EXAMPLES:BOOL=ON
                -Dagg_BUILD_PLATFORM:BOOL=ON
                -Dagg_USE_AGG2D:BOOL=ON
                -Dagg_USE_AGG2D_FREETYPE:BOOL=ON
                -Dagg_USE_FREETYPE:BOOL=ON
                -Dagg_USE_GPC:BOOL=ON
                -B "${{github.workspace}}/build" .

          - name: Build
            run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    GCC:
        runs-on: ubuntu-22.04
        name: ubuntu-22.04
        strategy:
            fail-fast: false
            matrix: 
               os: [ubuntu-22.04]


        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0
          
          - name: Install packages
            run: |
                sudo apt-get update
                sudo apt-get install -y gcc g++ cmake wget git libsdl1.2-dev libfreetype-dev libexpat1-dev 

          - name: Configure CMake
            run: >-
                cmake -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}"
                -Dagg_BUILD_CONTROLS:BOOL=ON
                -Dagg_BUILD_DEMO:BOOL=ON
                -Dagg_BUILD_EXAMPLES:BOOL=ON
                -Dagg_BUILD_PLATFORM:BOOL=ON
                -Dagg_USE_AGG2D:BOOL=ON
                -Dagg_USE_AGG2D_FREETYPE:BOOL=ON
                -Dagg_USE_EXPAT:BOOL=ON
                -Dagg_USE_FREETYPE:BOOL=ON
                -Dagg_USE_GPC:BOOL=ON
                -Dagg_USE_SDL_PLATFORM:BOOL=ON
                -B "${{github.workspace}}/build" .

          - name: Build
            run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
